- name: install nginx rpm
  yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm state=present

- name: install nginx
  yum: name=nginx state=present

- name: restart nginx
  service: name=nginx state=restarted

- name: chkconfig nginx
  command: chkconfig nginx on

- name: Install libselinux-python
  yum: name={{ item }} state=present
  with_items: 
    - libselinux-python

- name: copy nginx default_config 
  template: src=default{{ conf_type | default('') }}.conf.j2 dest=/etc/nginx/conf.d/default.conf mode=0644
