- command: /usr/bin/test -f /vagrant/{{wp_version}}.tar.gz 
  register: has_downloaded
  ignore_errors: True

- name: get wordpress
  get_url:
    url="https://ja.wordpress.org/{{wp_version}}.tar.gz"
    dest="/vagrant"
  when: has_downloaded|failed

- command: /usr/bin/test -d /vagrant/{{wp_version}}
  register: has_decomposed 
  ignore_errors: True

- name: defrost
  command: tar xzf {{wp_version}}.tar.gz
  args:
    chdir: "/vagrant"
  when: has_decomposed|failed

- name: Install mysql 
  yum: name={{ item }} state=present
  with_items: 
    - mysql-server 
    - mysql-devel
    - MySQL-python

- name: chkconfig mysqld
  command: chkconfig mysqld on

- name: restart mysql
  service: name=mysqld state=restarted

- mysql_user: name=develop password=develop priv=*.*:ALL,GRANT state=present

- mysql_db: name=wordpress state=present

- name: Install php 
  yum: name={{ item }} state=present
  with_items: 
    - php 
    - php-pdo
    - php-mysql
    - php-mbstring
    - php-fpm

- name: Install libselinux-python
  yum: name={{ item }} state=present
  with_items: 
    - libselinux-python

- name: copy nginx default_config 
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf mode=0644
