- name: Install libselinux-python
  yum: name=libselinux-python state=present

- command: /usr/bin/test -f /vagrant/{{wp_version}}.tar.gz 
  register: has_downloaded
  ignore_errors: True

- name: get wordpress
  get_url:
    url="https://ja.wordpress.org/{{wp_version}}.tar.gz"
    dest="/vagrant"
  when: has_downloaded|failed

- command: /usr/bin/test -d /vagrant/{{wp_version}}
  register: has_decomposed 
  ignore_errors: True

- name: defrost
  command: tar xzf {{wp_version}}.tar.gz
  args:
    chdir: "/vagrant"
  when: has_decomposed|failed

- name: copy wp-config 
  template: src=wp-config.php dest=/vagrant/wordpress/wp-config.php mode=0644
  when: has_decomposed|failed

- name: Install mysql 
  yum: name={{ item }} state=present
  with_items: 
    - mysql-server 
    - mysql-devel
    - MySQL-python

- name: chkconfig mysqld
  command: chkconfig mysqld on

- name: restart mysql
  service: name=mysqld state=restarted

- mysql_user: name=develop password=develop priv=*.*:ALL,GRANT state=present

- mysql_db: name=wordpress state=present

- name: Install php 
  yum: name={{ item }} state=present
  with_items: 
    - php 
    - php-pdo
    - php-mysql
    - php-mbstring
    - php-fpm

- name: restart php-fpm
  service: name=php-fpm state=restarted

- name: chkconfig php-fpm
  command: chkconfig php-fpm on

- name: install nginx rpm
  yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm state=present

- name: install nginx
  yum: name=nginx state=present

- name: copy nginx default_config 
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf mode=0644

- name: restart nginx
  service: name=nginx state=restarted

- name: chkconfig nginx
  command: chkconfig nginx on

- selinux: state=disabled

- name: insert iptables rule
  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="80"
              insertafter="^:OUTPUT " line="-A INPUT -p tcp --dport 80 -j ACCEPT"
