
- name: Install related libs 
  yum: name={{ item }} state=present
  with_items: 
    - gcc
    - python
    - python-devel
    - ncurses-devel
    - python-setuptools
    - perl-ExtUtils-Embed
    - git

- command: /usr/bin/test -f {{install_dir}}/bin/vim 
  register: vim_bin 
  ignore_errors: True

- name: clone 
  git: repo=https://github.com/vim/vim.git dest="{{local_srcdir}}/{{vim_srcdir}}"
  when: vim_bin|failed

- name: make 
  command: "{{item}}"
  args:
    chdir: "{{local_srcdir}}/{{vim_srcdir}}"
  with_items:
    - make distclean
    - "./configure --prefix={{install_dir}} {{configure_opt1}} {{configure_opt2}}"
    - make
    - make install
  when: vim_bin|failed
