- name: install epel repo.
  yum: name=epel-release state=present

- name: Install libselinux-python
  yum: name={{ item }} state=present
  with_items: 
    - nodejs
    - npm 
  
- name: install bower 
  command: npm install bower -g
