- command: /usr/bin/test -f /home/vagrant/.git-prompt.sh 
  register: has_downloaded 
  ignore_errors: True

- name: get git-completion
  get_url:
    url="https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash"
    dest="/home/vagrant/.git-completion.bash"
  when: has_downloaded|failed

- name: get git-propmt
  get_url:
    url="https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
    dest="/home/vagrant/.git-prompt.sh"
  when: has_downloaded|failed

- file: path=/home/vagrant/.git-completion.bash owner=vagrant group=vagrant state=file
  when: has_downloaded|failed

- file: path=/home/vagrant/.git-prompt.sh owner=vagrant group=vagrant state=file
  when: has_downloaded|failed

- file: path=/home/vagrant/.bash.d state=directory owner=vagrant group=vagrant
  when: has_downloaded|failed

- template: src=git_prompt.sh.j2 dest=/home/vagrant/.bash.d/git_prompt.sh mode=0766 owner=vagrant group=vagrant
  when: has_downloaded|failed

- lineinfile:
    dest="~/.bash_profile" state=present
    line="if [ -d ~/.bash.d ] ; then for f in ~/.bash.d/*.sh ; do [ -x \"$f\" ] && . \"$f\"; done; unset f; fi"
  sudo: no

- name: Install git 
  yum: name=git state=present

- name: clone 
  git: repo=git@github.com:hanhan1978/junks.git dest="~/junks" accept_hostkey=yes
  sudo: no

- file: src="~/junks/dotfiles/.vimrc" dest="~/.vimrc" state=link
  sudo: no

- file: dest="~/.vim/bundle" state=directory
  sudo: no

- git: repo=https://github.com/Shougo/neobundle.vim dest="~/.vim/bundle/neobundle.vim"
  sudo: no

- name: Install epel and tmux
  yum: name={{item}} state=present
  with_items: 
    - epel-release
    - tmux

- file: src="~/junks/dotfiles/.tmux.conf" dest="~/.tmux.conf" state=link
  sudo: no

