- name: install epel repo.
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-6.rpm state=present

- name: Install php56 
  yum: name={{ item }} state=present enablerepo=remi
  with_items: 
    - php56 
    - php56-xhprof 
    - php56-php-pdo
    - php56-php-mysqlnd
    - php56-php-mbstring
    - php56-php-fpm

- name: symlink 
  command: ln -fs /usr/bin/php56 /usr/bin/php 

- name: install composer 
  shell: curl -sS https://getcomposer.org/installer | php 

- name: move composer 
  command: "{{item}}"
  with_items:
    - mv composer.phar /usr/bin/composer 

- name: laravel installer
  command: composer global require "laravel/installer=~1.1"
  sudo: no

- name: add composer path 
  shell: echo "export PATH=$PATH:~/.composer/vendor/bin" >> ~/.bash_profile
  sudo: no

- name: copy php-fpm conf 
  template: src=www.conf.j2 dest=/opt/remi/php56/root/etc/php-fpm.d/www.conf mode=0644

- name: restart php-fpm 
  service: name=php56-php-fpm state=restarted

- name: chkconfig php-fpm 
  command: chkconfig php56-php-fpm on
